# Generated by Django 3.0.8 on 2021-01-20 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CrushIt', '0004_auto_20210119_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golf_player',
            name='player',
        ),
        migrations.AddField(
            model_name='golf_player',
            name='n',
            field=models.CharField(default='dummyName', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golf_player',
            name='s',
            field=models.CharField(default='dummy_short', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='golf_roundplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='CrushIt.Golf_player'),
        ),
    ]
