# Generated by Django 3.0.8 on 2021-01-21 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CrushIt', '0005_auto_20210120_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golf_course',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='golf_course',
            old_name='Cntry',
            new_name='cntry',
        ),
        migrations.RenameField(
            model_name='golf_course',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='golf_course',
            old_name='Tel',
            new_name='tel',
        ),
        migrations.AlterField(
            model_name='golf_roundplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='CrushIt.Golf_player'),
        ),
    ]
