# Generated by Django 3.1.6 on 2021-02-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrushIt', '0018_auto_20210201_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
