# Generated by Django 3.1.6 on 2021-02-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CrushIt', '0020_golf_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golf_tee',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tee', to='CrushIt.golf_course'),
        ),
    ]
